### ISSUE TITLE
Merge two TDigests throws NullPointerException

### ISSUE THREAD

**Issue by kevindai0126** [addthis/stream-lib#100]
Sometimes when I merged two tdigests by call the add method of one tdigest, it threw NullPointerException as follows:
java.lang.NullPointerException
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:85)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:79)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.GroupTree.add(GroupTree.java:81)
        at com.clearspring.analytics.stream.quantile.TDigest.add(TDigest.java:146)
        at com.clearspring.analytics.stream.quantile.TDigest.add(TDigest.java:171)

**Comment by tdunning** [comment]
Streamlib should use the AvlTreeDigest instead.

Faster.  Better.
